framework:
    notifier:
        #chatter_transports:
        #    slack: '%env(SLACK_DSN)%'
        #    telegram: '%env(TELEGRAM_DSN)%'
        #texter_transports:
        #    twilio: '%env(TWILIO_DSN)%'
        #    nexmo: '%env(NEXMO_DSN)%'
        chatter_transports:
            discord: '%env(DISCORD_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email']
            low: ['chat/discord']
            contact: ['email','chat/discord']
        admin_recipients:
            - { email: '%env(ADMIN_RECIPIENT)%' }
