sonata_seo:
  encoding: UTF-8
  page:
    title: 'Robin PARISOT - Développeur WEB Fullstack'
    separator: ' - '
    # title_prefix:  'Prefix |'
    #    title_suffix:  '- Robin PARISOT - Développeur WEB Fullstack'
    default: sonata.seo.page.default
    metas:
      name:
        description: Robin PARISOT, développeur web full stack spécialisé en Symfony. Création de sites web performants et optimisés pour le référencement naturel. Contactez-moi pour vos projets de développement web.
        robots: index, follow

      property:
        # Facebook application settings
        #'fb:app_id':          XXXXXX
        #'fb:admins':          admin1, admin2

        # Open Graph information
        # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
        'og:type': website
        'og:locale': fr_FR
        'og:title': Robin PARISOT - Développeur WEB Fullstack
        'og:description': Robin PARISOT, développeur web full stack spécialisé en Symfony. Création de sites web performants et optimisés pour le référencement naturel. Contactez-moi pour vos projets de développement web.
      http-equiv:
        'Content-Type': text/html; charset=utf-8
        #'X-Ua-Compatible':      IE=EmulateIE7

      charset:
        UTF-8: ''

    head:
      'xmlns': http://www.w3.org/1999/xhtml
      'xmlns:og': http://opengraphprotocol.org/schema/
      #'xmlns:fb':           "http://www.facebook.com/2008/fbml"