vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        actualities:
            uri_prefix: /uploads/actualities
            upload_destination: '%kernel.project_dir%/public/uploads/actualities'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true